theme: jekyll-theme-minimal
title: [Deep Face Recognition: A tutorial]
description: [Tutorial at SIBRAPI 2018]
logo: [https://github.com/isi-vista/deep-face-recognition-tutorial/blob/master/logo.png]
